#!/usr/bin/env bun

import console from 'console';
import { mkdirSync, existsSync, readFileSync } from 'fs';
import { dirname, join, resolve, relative, isAbsolute } from 'node:path';
import { parseArgs } from 'node:util';
import { fileURLToPath } from 'url';

import type { FSWatcher } from 'chokidar';
import { watch } from 'chokidar';
import { type TsConfigResult, type TsConfigJson, parseTsconfig } from 'get-tsconfig';
import { format as formatWithOxfmt } from 'oxfmt';

import { colorText } from '../utils/cli.js';
import { writeIfDifferent } from '../utils/fs.js';
import { isDirectExecution } from './utils.js';

// TODO on startup check cwd for oxfmt config and use that instead of my default

const DEFAULT_TEST_EXCLUDES = [
  '**/*.test.ts',
  '**/*.test.tsx',
  '**/*.spec.ts',
  '**/*.spec.tsx',
  '**/__tests__/**',
  '**/tests/**'
];
export const GENERATED_FILE_HEADER = '// generated by ts-build-config';

const LABEL = colorText('cyan', '[ts-build-config]');
const formatPath = (filePath: string): string => colorText('dim', relative(process.cwd(), filePath));
const logInfo = (message: string): void => console.log(`${LABEL} ${message}`);
const logWarn = (message: string): void => console.warn(`${LABEL} ${colorText('yellow', message)}`);
const logError = (message: string): void => console.error(`${LABEL} ${colorText('red', message)}`);

export function unique(items: string[]): string[] {
  return Array.from(new Set(items));
}

/**
 * If the path refers to a file then it returns it otherwise joins tsconfig.json
 */
export function resolveTsConfigPath(refAbsPath: string): string {
  if (refAbsPath.endsWith('.json')) return refAbsPath;
  else return join(refAbsPath, 'tsconfig.json');
}

/**
 * Excludes extra paths from the include list that contain test patterns
 */
export function computeExtraExcludes(config: TsConfigJson): string[] {
  const extra: string[] = [...DEFAULT_TEST_EXCLUDES];

  // If the tsconfig includes ./tests (or tests) explicitly, ensure it is excluded in build config.
  for (const inc of config.include ?? []) {
    const norm = inc.replace(/\\/g, '/').replace(/\/+$/, '');
    if (norm === './tests' || norm === 'tests' || norm.startsWith('./tests/') || norm.startsWith('tests/')) {
      extra.push('./tests/**');
      break;
    }
  }

  return unique(extra);
}

export function withTrailingNewline(value: string): string {
  return value.endsWith('\n') ? value : `${value}\n`;
}

export async function formatBuildTsconfigJson(config: TsConfigJson): Promise<string> {
  const fallback = JSON.stringify(config, null, 2);

  try {
    const result = await formatWithOxfmt('tsconfig.build.json', fallback, {
      useTabs: false,
      singleQuote: true,
      trailingComma: 'none',
      printWidth: 120,
      objectWrap: 'collapse',
      semi: true,
      proseWrap: 'always',
      sortPackageJson: { sortScripts: true },
      sortImports: {}
    });
    if (!result.errors.length && typeof result.code === 'string' && result.code.length > 0) {
      return withTrailingNewline(result.code);
    }
  } catch {
    // Fallback to plain JSON below.
  }

  return withTrailingNewline(fallback);
}

export async function writeBuildTsconfig(tsconfigPath: string, config: TsConfigJson, dryRun: boolean): Promise<string> {
  const dir = dirname(tsconfigPath);
  const outPath = join(dir, 'tsconfig.build.json');

  const mergedExclude = unique([...(config.exclude ?? []), ...computeExtraExcludes(config)]);

  const buildConfig: TsConfigJson = { extends: './tsconfig.json', compilerOptions: {}, exclude: mergedExclude };

  if (config.references && config.references.length > 0) buildConfig.references = config.references;

  // If original compilerOptions exists, keep build-specific overrides minimal.
  // But ensure emit is enabled if base tsconfig has noEmit: true (common for editor configs).
  if (config.compilerOptions?.noEmit === true) buildConfig.compilerOptions!.noEmit = false;

  // Keep outDir/rootDir if already set in base; do not guess.
  // If you want to force them, do it in the base tsconfig.json or pass flags later.

  if (!dryRun) {
    mkdirSync(dir, { recursive: true });
    const formattedJson = await formatBuildTsconfigJson(buildConfig);
    const text = `${GENERATED_FILE_HEADER}\n${formattedJson}`;

    await writeIfDifferent(outPath, text);
  }

  return outPath;
}

export function isGeneratedByThisScript(filePath: string): boolean {
  try {
    const contents = readFileSync(filePath, 'utf8');
    const firstLine = contents.split(/\r?\n/, 1)[0]?.trim() ?? '';

    return firstLine === GENERATED_FILE_HEADER;
  } catch {
    return false;
  }
}

/**
 * @returns true if the tsconfig path should have a build config generated for it
 */
export function shouldUseBuildConfig(tsconfigPath: string, force: boolean): boolean {
  const buildPath = join(dirname(tsconfigPath), 'tsconfig.build.json');
  if (!existsSync(buildPath)) return true;
  if (force) return true;
  return isGeneratedByThisScript(buildPath);
}

export function ensureDotRelative(filePath: string): string {
  if (filePath.startsWith('.')) return filePath;
  return `./${filePath}`;
}

/**
 * Returns the modified tsconfig where the references point to the build configs
 * (that we are going to build)
 */
export function replaceRefsWithBuildConfigs(
  res: TsConfigResult,
  buildConfigSet: Set<string>,
  remove: string[]
): TsConfigJson {
  const refs = res.config.references;
  if (!refs || refs.length === 0) return res.config;

  // console.log('refs', res.path, refs);
  const baseDir = dirname(res.path);
  const mapped: TsConfigJson.References[] = refs
    .map((ref) => {
      const refPath = ensureDotRelative(ref.path);
      const absPath = resolve(dirname(res.path), refPath);
      const resolvedRefPath = resolveTsConfigPath(absPath);

      if (remove.includes(resolvedRefPath)) {
        return undefined;
      }

      if (!buildConfigSet.has(resolvedRefPath)) {
        // We're not going to build this one so use it plain
        return { ...ref, path: refPath };
      }

      const buildRefPath = join(dirname(resolvedRefPath), 'tsconfig.build.json');
      const relativeBuildRef = ensureDotRelative(relative(baseDir, buildRefPath));
      return { ...ref, path: relativeBuildRef };
    })
    .filter((v) => v !== undefined);

  return { ...res.config, references: mapped };
}

export type GenerateOptions = { dryRun: boolean; force: boolean; verbose: boolean; remove: string[] };

export async function generateBuildConfigs(
  entry: string,
  options: GenerateOptions
): Promise<{ created: { src: string; out: string }[]; visitedConfigs: string[] }> {
  const { dryRun, force, verbose } = options;

  const loadedConfigs = new Map<string, TsConfigResult>();
  const visited = new Set<string>();
  const queue: string[] = [entry];
  const created: { src: string; out: string }[] = [];

  // First pass: discover the full referenced tsconfig graph and load configs.
  while (queue.length) {
    const tsconfigPath = queue.shift()!;
    if (visited.has(tsconfigPath)) continue;
    visited.add(tsconfigPath);

    let res: TsConfigResult;

    try {
      const config = parseTsconfig(tsconfigPath);
      if (config) res = { path: tsconfigPath, config };
      else throw new Error('Null returned from getTsConfig');
    } catch (e) {
      logWarn(`Skipping unreadable config: ${formatPath(tsconfigPath)}`);
      if (verbose) console.warn(e);
      continue;
    }

    loadedConfigs.set(res.path, res);

    const refs = unique(
      (res.config.references ?? []).map((ref) => {
        const abs = resolve(dirname(res.path), ref.path);
        return resolveTsConfigPath(abs);
      })
    );
    for (const r of refs) queue.push(r);
  }

  const discoveredConfigs = Array.from(loadedConfigs.keys()).filter((path) => !isGeneratedByThisScript(path));
  const buildConfigSet = new Set(discoveredConfigs.filter((path) => shouldUseBuildConfig(path, force)));

  // Second pass: write build configs with rewritten references.
  for (const tsconfigPath of discoveredConfigs) {
    const res = loadedConfigs.get(tsconfigPath)!;
    const buildPath = join(dirname(tsconfigPath), 'tsconfig.build.json');

    if (!buildConfigSet.has(tsconfigPath)) {
      if (verbose) {
        logInfo(`Skip ${formatPath(buildPath)} (manual file, use ${colorText('bold', '--force')})`);
      }
    } else {
      const rewrittenCfg = replaceRefsWithBuildConfigs(res, buildConfigSet, options.remove);
      const written = await writeBuildTsconfig(tsconfigPath, rewrittenCfg, dryRun);
      created.push({ src: tsconfigPath, out: written });
      if (verbose || dryRun) {
        const verb = dryRun ? colorText('yellow', '[dry-run] write') : colorText('green', 'write');
        logInfo(`${verb} ${formatPath(written)} <- ${formatPath(tsconfigPath)}`);
      }
    }
  }

  if (!verbose && !dryRun) {
    logInfo(`${colorText('green', 'updated')} ${created.length} tsconfig.build.json file(s)`);
  }

  return { created, visitedConfigs: Array.from(visited) };
}

export function createRegenerator(
  entry: string,
  options: GenerateOptions
): { run: (reason?: string) => Promise<void>; syncWatchedConfigs: (watcher: FSWatcher) => void } {
  let isRunning = false;
  let rerunRequested = false;
  let watchedConfigs = new Set<string>();

  const syncWatchedConfigs = (watcher: FSWatcher): void => {
    if (watchedConfigs.size === 0) return;
    watcher.add(Array.from(watchedConfigs));
  };

  const run = async (reason?: string): Promise<void> => {
    if (isRunning) {
      rerunRequested = true;
      return;
    }
    isRunning = true;

    try {
      do {
        rerunRequested = false;
        if (reason) {
          logInfo(`${colorText('cyan', 'regenerate')} (${reason})`);
          reason = undefined;
        }
        const result = await generateBuildConfigs(entry, options);
        watchedConfigs = new Set(result.visitedConfigs);
      } while (rerunRequested);
    } finally {
      isRunning = false;
    }
  };

  return { run, syncWatchedConfigs };
}

export async function main(): Promise<void> {
  const { values } = parseArgs({
    args: process.argv.slice(2),
    options: {
      config: { type: 'string', short: 'c' },
      dryRun: { type: 'boolean' },
      force: { type: 'boolean' }, // overwrite files not generated by this script
      watch: { type: 'boolean', short: 'w' },
      verbose: { type: 'boolean', short: 'v' },
      remove: { type: 'string' } // abs paths to tsconfig refs to remove
    }
  });

  const entry = values.config ? resolve(values.config) : null;
  if (!entry) {
    logError('Missing required flag: --config <path/to/tsconfig.json>');
    process.exit(1);
  }
  if (!existsSync(entry)) {
    logError(`Config file not found: ${formatPath(entry)}`);
    process.exit(1);
  }

  const dryRun = values.dryRun === true;
  const force = values.force === true;
  const watchMode = values.watch === true;
  const verbose = values.verbose === true;
  const remove = (values.remove?.split(' ') ?? []).map((path) =>
    isAbsolute(path) ? path : resolve(process.cwd(), path)
  );
  const options: GenerateOptions = { dryRun, force, verbose, remove };

  const regenerator = createRegenerator(entry, options);
  await regenerator.run('initial run');

  if (!watchMode) return;

  logInfo(`watching ${colorText('cyan', 'tsconfig')} changes...`);
  const watcher = watch([], {
    persistent: true,
    ignoreInitial: true,
    awaitWriteFinish: { stabilityThreshold: 300, pollInterval: 100 }
  });
  regenerator.syncWatchedConfigs(watcher);

  watcher.on('change', async (filePath) => {
    logInfo(`${colorText('cyan', 'change')} ${formatPath(filePath)}`);
    await regenerator.run(`changed ${relative(process.cwd(), filePath)}`);
    regenerator.syncWatchedConfigs(watcher);
  });

  watcher.on('add', async (filePath) => {
    logInfo(`${colorText('cyan', 'add')} ${formatPath(filePath)}`);
    await regenerator.run(`added ${relative(process.cwd(), filePath)}`);
    regenerator.syncWatchedConfigs(watcher);
  });

  watcher.on('unlink', async (filePath) => {
    logInfo(`${colorText('yellow', 'remove')} ${formatPath(filePath)}`);
    await regenerator.run(`removed ${relative(process.cwd(), filePath)}`);
    regenerator.syncWatchedConfigs(watcher);
  });
}

if (isDirectExecution(import.meta.url)) {
  main().catch((err) => {
    logError('Unhandled error');
    console.error(err);
    process.exit(1);
  });
}
